Add Hardware to Benchmark
osuTitanic/stern pull request #200
Opened 2024-09-01 20:35 UTC by Digitalfear117

2024-09-04 15:38 UTC, Lekuruu requested changes
Before I do an actual review here, please rebase your branch to the latest stern commit. It seems like the branch was outdated.

2024-09-09 14:03 UTC, Lekuruu requested changes

2024-09-09 14:03 UTC, Lekuruu commented on app/models/benchmark.py
> +    hardware: str
Shouldn't this be a dict?

2024-09-09 21:35 UTC, Digitalfear117 commented on app/models/benchmark.py
> +    hardware: str
Yes, I have now updated it to dict

2024-09-10 15:52 UTC, Lekuruu approved these changes

2024-09-10 15:53 UTC, merged